### ISSUE TITLE
Can I use moonboots in a route module?

### ISSUE THREAD

**Issue by elmarburke** [lukekarrys/moonboots-express#2]
I want to use moonboots in a express app where the [routes are separated into modules](http://expressjs.com/api#router). There is a myApp-www module in which the front end stuff should land.

Can I use moonboots in such a case in the myApp-www module?

**Comment by elmarburke** [comment]
Just do it - it worked!

```
var express = require('express');
var Moonboots = require('moonboots-express');
var router = express.Router();

new Moonboots({
    server: router,
    moonboots: {
        main: __dirname + '/app/app.js'
    }
});

module.exports = router;
```

**Comment by lukekarrys** [comment]
Glad it worked @elmarburke! I'm going to close this but feel free to reopen and let me know if anything doesn't work.
